spring.application.name=rabbitMQ
server.port=8080

# H2
spring.datasource.url=jdbc:h2:mem:consumidorDb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true
spring.jpa.hibernate.ddl-auto=create-drop

# RabbitMQ (mismo cluster que el productor)
spring.rabbitmq.host=3.92.151.242
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123

# AWS S3
spring.cloud.aws.region.static=us-east-1
aws.s3.bucket=mslpbucket